### ISSUE TITLE
Two Counters For Screen Off

### ISSUE THREAD

**Issue by ppublicgit** [bugsounet/MMM-NewPIR#33]
I just updated to the new version and there is an issue with the counter. There are seemingly two simultaneous counters, located in the same position. Both start counting down at the same time but once I trigger the PIR, one counter resets and the other just continues counting down. This results in the counter quickly flashing between the two times (say 3:00 then 2:00 then 2:59 then 1:59 etc.). The one timer never resets, while the other will reset each time the pir sensor is triggered. Then, Once the timer that won't reset hits 0, it acts as it should and shuts off the screen. It is not possible to bring the screen back since that timer never seems to register the user presence events. 

This issue seems fairly similar to issue #32 but I am only running a single instance of magic mirror (or at least I am fairly certain I am). I do not use pm2 or autolaunch and instead always launch from a call to "node serveronly" and then accessing the magicmirror via chromium and localhost.

Thanks.

**Comment by bugsounet** [comment]
Hi, it's the same response, like #32 
by using node serveronly :
ALL module loaded are launched as many times as you run chronium ... but it's displayed IN the same screen.
example:
* calandar module fetch x times, and display one time (there is no probleme because it's the same value but you flood for fetch value and can return an error)
* weather module flood fetch and return no value
* telegrambot refuses new connection because you are already logged
* Spotify module flood fetch and return no value

EVERY developer can't resolve this issue. (and for OTHER modules)
-> EVERY modules for magicmirror are develloped for ONE instance of run
the best way is using VNC embed RPI program.
It's copy the entire display to another computer (with mouse and keybord support)

If you want really use node serveronly, don't use this module. but you will have the same issue with other equal module

**Comment by ppublicgit** [comment]
Okay. So if I were to run with npm start instead, would this not cause an issue with dual counters? I assume still running the module with node serveronly but turning off the display would have no affect on the issue as well.

**Comment by bugsounet** [comment]
by it's using chrome or other browser for remote displaying MagicMirror
the result is relaunch the main core in a single display screen.
MM core don't manage the multiple intence

**Comment by ppublicgit** [comment]
Okay, thank you. I am closing this issue.
